# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DemoJsonOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Overcoat', '~> 4.0.0-beta.1'

  #payment lib
  pod 'Braintree'
  pod 'Braintree/PayPal'
  pod 'Braintree/3D-Secure'
  pod 'Braintree/DataCollector'

  # Pods for DemoJsonOC
  target 'DemoJsonOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
